Fix build error due to decl after case
Fixes the following error:

    ../main.c:267:4: error: expected expression
                            char *end = NULL;
                            ^